// Compact 112-bar melody and harmony map for Shadowline.
// The data contains only MIDI note and chord events for procedural synthesis.

const ROOT_DATA = "FFFFFFFFFPNFFFKFOIFFKPKIFNNHKFFFFINFFFFFOPNFFFFFQPPFNPPKGMKHHHMKFPKMFKMFMFPMFFFKFFIMFLPKPGFKOGFFFMKIHFFFFFFKPPPP";
const KIND_DATA = "ABAEADFEFBCEAAAADAADEAFBACCCAFFEAACDAEEAEBCDEAFCGBBBABFFCDDGEEEAABFBEAEADBBADAAAAAABFCBCBCBDCCAEAECAGDFDEEFACCCA";
const MELODY_DATA = "AARAAAYAABRAABYAAB87ACBHACMAACREAChCACsAACw+AC8AADFHADdCADo9ADsAADw+AD09AD8AAEFHAERJAEYAAEhFAExDAE5BAE9CAFIAAFQ7AFU+AFc7AFk+AFwAAF47AF9HAGUAAGZEAGhCAGo/AGtAAGwAAHBCAHFHAHNMAHRJAHVHAHZEAHdCAHo/AHsAAH09AH5AAH9CAIA/AIFHAINLAIRJAIZCAIdAAIhKAItMAI1HAI5BAI9AAJBCAJI7AJQ9AJY+AJk7AJsAAJ08AJ8AAKA7AKFHAKJKAKNMAKROAKZMAKhCAKkAAKpMAK9QALAAALFOALJDALNJALRMALVOALZNALdMALhJALlKALpMALtOALxTAL1HAL5PAL9MAMAAAME7AMI/AMMAAMVCAMgAAMk+AMpCAMtDAMwAAM1HANFFANIAANNHANdAANhIANlHANtIANxEAN1CAN5HAN8/AOBCAOFEAOlCAOw+AO9AAPBCAPFEAPIAAPNHAPhEAPk+APoAAPxAAP89AQA+AQEAAQJEAQNHAQZJAQgAAQtKAQ5MAQ9HARFMARJOARNDARQAARZJARdKARxHAR1FAR4AAR9TASFHASIAASNCASREAShCASlAASsAASw+AS1AAS4AAS8+ATBAATE9ATI+ATQ7ATU/ATYAATdCATsAATw+AT09AUBCAUFEAUJJAUNLAUREAUVJAU1CAU5FAU9HAVBBAVFEAVIAAVNHAVVCAVZBAVdAAVg/AVk7AV8+AWEAAWdEAWhCAWo/AWw9AW1CAXJHAXVLAXlJAXpHAXtGAXxCAX1EAX4/AX9CAYE/AYYAAYg9AYoAAYw9AY4+AY8AAZI8AZM9AZUAAZ1HAaBTAatOAaw9Aa1JAbAAAbNOAbRMAbVHAbZFAbdOAbhMAblKAbpJAbtFAbxHAb1JAb5FAb9AAcA+AcFDAcQAAcZCAcdDAcg9AckAAc1AAc4/AdFAAdMAAdU+AdZBAddCAdlBAdpAAdtIAd5HAd9GAeBFAeJEAeVCAeZFAelEAepAAes+AewAAe5AAfA9AfE+AfJAAfNCAfdHAfhJAfpMAf0AAgFTAghPAgoAAg1RAg5MAg9IAhBRAhFNAhJMAhNKAhRJAhVDAhlAAhpBAhtCAhxAAh07Ah4AAiA+AiIAAiVHAidAAikAAipEAi5CAjA9AjFAAjM9AjQ+AjZCAjdHAjxEAj5DAj9CAkI+AkM9AkQ7AkUAAklHAkxJAk0AAlBCAlFFAlRHAlUAAlZDAldCAlk7AlsAAl0+AmA7AmI+AmUAAmg7AmoAAnY7Ans9AnxMAn1AAn49An9MAoBAAoE/AoI7AoQAAoZCAotHAo9JApAAApNKApZCApdMAppOAptDAp4AAp9AAqBKAqFEAqJCAqZDAqcAAq1KAq5MAq9OArBPArFMArJKArNJArRDArVKArZOArdMArhFAroAArxOAr1MAsBOAsFNAsJMAsZOAshTAspHAstMAswAAs9OAtBMAtFIAtJOAtMAAtRLAtZMAtdOAtgAAtlPAtwAAt1SAt5MAuBTAuMAAuZNAuhMAupNAusAAu5TAvFMAvJOAvNQAvRPAvVOAvdKAvhMAvlJAvpKAvtMAvxJAv0AAv9TAwRQAwVOAwcAAwhKAwlJAw1DAw5EAw9HAxNJAxZDAxcAAxhKAxxMAx9NAyBOAyFDAyIAAyRAAyVGAyZKAyhHAytEAyxCAy9EAzEAAzJCAzREAzgAAzxAAz4AA0FCA0RAA0UAA0lCA0xEA1FCA1IAA1ZFA1gAA2BAA2FJA2JQA2NMA2dQA2lMA29AA3BEA3FMA3NEA3gAA3lAA3sA";

const KINDS = ["major", "dominant", "major7", "minor", "minor7", "minor6", "diminished"] as const;
export type ShadowlineChordKind = (typeof KINDS)[number];

export const SHADOWLINE_SCORE_ROOTS = [...ROOT_DATA].map((value) => value.charCodeAt(0) - 65 + 29);
export const SHADOWLINE_SCORE_KINDS = [...KIND_DATA].map((value) => KINDS[value.charCodeAt(0) - 65]);

export const SHADOWLINE_MELODY_EVENTS: Record<number, number> = {};
const melodyBytes = Uint8Array.from(atob(MELODY_DATA), (value) => value.charCodeAt(0));
for (let index = 0; index < melodyBytes.length; index += 3) {
  const step = melodyBytes[index] * 256 + melodyBytes[index + 1];
  SHADOWLINE_MELODY_EVENTS[step] = melodyBytes[index + 2] - 1;
}
